### ISSUE TITLE
게시판에 대한 접근 부여

### ISSUE THREAD

**Issue by hogueny** [hogueny/study-vue#14]
공지게시판 - admin 속성을 가진 사용자만이 게시판 메시지 작성가능
자유게시판 - nomal 속성을 가진 사용자 또는 admin속성을 가진 사용자가 메시지 작성 모두 가능함

**Comment by taehyoung** [comment]
board 테이블에 권한에 대해 명시하는 칼럼을 추가하는 건 어떰?


나중에 자유게시판도 admin만 쓰게 하고 싶다고 하면,  코드를 바꿔야 하니까

**Comment by hogueny** [comment]
굿

**Comment by hogueny** [comment]
board role 과 user role이 일치하면 접근
